AWSTemplateFormatVersion: '2010-09-09'
Description: SSL certificate for cell that includes stop.sb.seibtribe.us

Parameters:
  DomainName:
    Type: String
    Default: sb.seibtribe.us
    Description: The base domain name
  CellId:
    Type: String
    Description: The cell identifier (e.g., us-east-1-az1)

Resources:
  # SSL certificate for cell that includes stop domain
  CellStopCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub 'cell-${CellId}.${DomainName}'
      SubjectAlternativeNames:
        - !Sub 'stop.${DomainName}'
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: ARN of the certificate
    Value: !Ref CellStopCertificate
    Export:
      Name: !Sub '${AWS::StackName}-certificate-arn'